-- AlterTable
ALTER TABLE "Role" ADD COLUMN     "createdBy" TEXT NOT NULL DEFAULT 'root',
ADD COLUMN     "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "status" BOOLEAN NOT NULL DEFAULT false;
